# TypeProf 0.30.1

# lib/canvas.rb
class Canvas
  def height: -> Integer
  def width: -> Integer
  def pixels: -> Array[untyped]
  MAX_COLORS: Integer
  def initialize: (width: Integer, height: Integer) -> void
  def to_ppm: -> String
  def write_pixel: (row: Integer, col: Integer, color: Color) -> Array[untyped]?
  def pixel_at: (row: Integer, col: Integer) -> Array[untyped]?
  def to_s: -> String
  def ppm_header: -> String
  def ppm_body: -> String
  def ppm_footer: -> String
end
