# TypeProf 0.30.1

# lib/tuple.rb
class Tuple
  def x: -> Float
  def y: -> Float
  def z: -> Float
  def w: -> Float
  def initialize: (x: Float, y: Float, z: Float, w: Float) -> void
  def *: (Float) -> Tuple
  def /: (Float) -> Tuple
  def +: (Tuple) -> Tuple
  def -: (Tuple) -> Tuple
  def dot: (Tuple) -> Float
  def negate: -> Tuple
  def magnitude: -> Float
  def ==: (Tuple) -> bool
  def point?: -> bool
  def vector?: -> bool
end
