- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.277
  hooks:
    - id: ruff
      # Ruff options.
      args: ["--paths", "src", "tests", "--exclude", "src/ignore.py"]
