language: elixir
elixir:
  - 1.8
otp_release:
  - 20.3
sudo: false

env:
  - MIX_ENV=test

before_script:
  - mix deps.get

script:
  - mix test
  - mix coveralls.travis

after_script:
  - MIX_ENV=docs mix deps.get
