version: 2.1
jobs:
  build:
    parallelism: 2
    docker:
      - image: circleci/elixir:1.8
        environment:
          MIX_ENV: test

    working_directory: ~/app

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - run: mix test

