# TypeProf 0.30.1

# lib/color.rb
class Color
  def red: -> Float
  def green: -> Float
  def blue: -> Float
  def initialize: (red: Float, green: Float, blue: Float) -> void
  def +: (Color) -> Color
  def -: (Color) -> Color
  def *: (Color|Float) -> Color
  def deconstruct: -> [Float, Float, Float]
  def deconstruct_keys: (untyped) -> Hash[:blue | :green | :red, untyped]
  def to_s: -> String
  def ==: (Color) -> bool
end
