require_relative "rayz/canvas"
require_relative "rayz/chapter1"
require_relative "rayz/chapter2"
require_relative "rayz/chapter3"
require_relative "rayz/chapter4"
require_relative "rayz/chapter5"
require_relative "rayz/chapter6"
require_relative "rayz/color"
require_relative "rayz/intersection"
require_relative "rayz/lighting"
require_relative "rayz/material"
require_relative "rayz/point"
require_relative "rayz/point_light"
require_relative "rayz/ray"
require_relative "rayz/runner"
require_relative "rayz/sphere"
require_relative "rayz/transformations"
require_relative "rayz/tuple"
require_relative "rayz/util"
require_relative "rayz/vector"

module Rayz
end
