#!/usr/bin/env -S ruby --yjit

require_relative "../lib/rayz"
require_relative "chapter1"
require_relative "chapter2"
require_relative "chapter3"
require_relative "chapter4"
require_relative "chapter5"
require_relative "chapter6"
require_relative "chapter7"
require_relative "chapter8"
require_relative "chapter9"
require_relative "chapter10"
require_relative "chapter11"
require_relative "chapter12"
require_relative "chapter13"
require_relative "chapter14"
require_relative "chapter15"
require_relative "chapter16"
require_relative "chapter17"
require_relative "obj_parser_demo"
require_relative "nested_groups_demo"
require_relative "bounding_boxes_demo"
require_relative "advanced_features_demo"

module Rayz
  class ExamplesRunner
    CHAPTERS = {
      1 => Chapter1,
      2 => Chapter2,
      3 => Chapter3,
      4 => Chapter4,
      5 => Chapter5,
      6 => Chapter6,
      7 => Chapter7,
      8 => Chapter8,
      9 => Chapter9,
      10 => Chapter10,
      11 => Chapter11,
      12 => Chapter12,
      13 => Chapter13,
      14 => Chapter14,
      15 => Chapter15,
      16 => Chapter16,
      17 => Chapter17
    }

    DEMOS = {
      "obj_parser" => ObjParserDemo,
      "nested_groups" => NestedGroupsDemo,
      "bounding_boxes" => BoundingBoxesDemo,
      "advanced_features" => AdvancedFeaturesDemo
    }

    def self.run_all
      # Run all book chapters first (1-17)
      CHAPTERS.keys.sort.each do |chapter_num|
        CHAPTERS[chapter_num].run
      end

      # Then run all demos
      DEMOS.keys.sort.each do |demo_name|
        DEMOS[demo_name].run
      end
    end

    def self.run_chapter(num)
      chapter = CHAPTERS[num]
      if chapter
        chapter.run
      else
        puts "Error: Chapter #{num} does not exist."
        puts "Available chapters: 1-#{CHAPTERS.keys.max}"
        exit 1
      end
    end

    def self.run_demo(name)
      demo = DEMOS[name]
      if demo
        demo.run
      else
        puts "Error: Demo '#{name}' does not exist."
        puts "Available demos: #{DEMOS.keys.sort.join(", ")}"
        exit 1
      end
    end

    def self.usage
      puts "Usage: ruby examples/run [all|<chapter_number>|<demo_name>]"
      puts ""
      puts "Examples:"
      puts "  ruby examples/run all              # Run all chapters and demos"
      puts "  ruby examples/run 4                # Run only chapter 4"
      puts "  ruby examples/run obj_parser       # Run OBJ parser demo"
      puts "  ruby examples/run                  # Run all chapters and demos (default)"
      puts ""
      puts "Available chapters: 1-#{CHAPTERS.keys.max}"
      puts "Available demos: #{DEMOS.keys.sort.join(", ")}"
    end

    def self.parse_and_run(args)
      if args.empty? || args.first == "all"
        run_all
      elsif /^\d+$/.match?(args.first)
        chapter_num = args.first.to_i
        run_chapter(chapter_num)
      elsif DEMOS.key?(args.first)
        run_demo(args.first)
      else
        usage
        exit 1
      end
    end
  end
end

if __FILE__ == $0
  Rayz::ExamplesRunner.parse_and_run(ARGV)
end
