name: Lint (Ruby)

on:
  push:
    paths:
      - 'ruby/**'
  pull_request:
    paths:
      - 'ruby/**'

permissions:
  contents: read
  checks: write

jobs:
  standard:
    name: StandardRB Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.2
          bundler-cache: true
          working-directory: ruby
      - name: Run standardrb
        run: |
          set -e
          cd ruby
          bundle exec standardrb
