name: Lint

on: [push, pull_request]
permissions:
  contents: read
  pull-requests: write

jobs:
  standard:
    name: StandardRB Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
      - name: Run standardrb
        uses: kmcphillips/standardrb-action@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}