name: Lint

on: [push, pull_request]
permissions:
  contents: read
  checks: write

jobs:
  standard:
    name: StandardRB Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true
      - name: Run standardrb
        run: |
          set -e
          bundle exec standardrb

  steep:
    name: Steep static type checking
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true
      - name: Run Steep
        run: |
          set -e
          bundle exec steep check
