name: Lint (Shell)

on:
  push:
    paths:
      - '**/*.sh'
  pull_request:
    paths:
      - '**/*.sh'

permissions:
  contents: read
  checks: write

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run shellcheck
        run: |
          find . -name '*.sh' -print0 | xargs -0 shellcheck
