name: reviewdog

on: [push, pull_request]

jobs:
  steep:
    name: runner / steep
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true
      - name: steep check
        uses: tk0miya/action-steep@v1
