name: Test (Ruby)

on:
  push:
    paths:
      - 'ruby/**'
  pull_request:
    paths:
      - 'ruby/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.2
          bundler-cache: true
          working-directory: ruby
      - run: |
          set -e
          cd ruby
          bundle exec cucumber
